### ISSUE TITLE
迷宫走路有问题

### ISSUE THREAD

**Issue by Xiao-yux** [EtherLeaF/nonebot_plugin_maze#1]
![image](https://user-images.githubusercontent.com/79674967/185824268-988288ef-5849-46f8-ae30-c04fbfd7c86c.png)
![image](https://user-images.githubusercontent.com/79674967/185824282-f21d7a93-4407-42d0-bf4f-8777922ff290.png)
你这个迷宫是自动的吗？

**Comment by Xiao-yux** [comment]
你能把方向键换个阳间点的吗？比如w(上)，a(左),s(下),d(右)，或者中文也可以啊。
自己没找到方向键的位置在哪，不会改

**Comment by thetapilla** [comment]
一次移动操作为向该方向所在的路径**一直走**直到遇到下一个决策点（岔路口）因为一个一个数格子移动更加阴间。
图片中属于出现了一条长且无决策点的路径。
至于方向键的问题之后会考虑加入在.env中自定义的功能。
目前正在编写接入[nonebot-plugin-PicMenu](https://github.com/hamo-reid/nonebot_plugin_PicMenu)以方便用户获取详细帮助。

**Comment by thetapilla** [comment]
新版本v0.2.2已加入自定义方向键功能。
